// ─── Application Error Codes ───────────────────────────────────────────────────
export const ERROR_CODES = {
  // Generic
  INTERNAL: 'INTERNAL_ERROR',
  VALIDATION: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  BAD_REQUEST: 'BAD_REQUEST',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',

  // Database
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED: 'DB_QUERY_FAILED',
  DB_RECORD_NOT_FOUND: 'DB_RECORD_NOT_FOUND',
  DB_UNIQUE_VIOLATION: 'DB_UNIQUE_VIOLATION',

  // AI/Chat
  AI_SERVICE_UNAVAILABLE: 'AI_SERVICE_UNAVAILABLE',
  AI_CONTEXT_TOO_LONG: 'AI_CONTEXT_TOO_LONG',
  AI_RESPONSE_FAILED: 'AI_RESPONSE_FAILED',

  // FIR/Case
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CASE_ALREADY_CLOSED: 'CASE_ALREADY_CLOSED',

  // Analytics
  ANALYTICS_RANGE_INVALID: 'ANALYTICS_RANGE_INVALID',

  // Graph
  GRAPH_ENTITY_NOT_FOUND: 'GRAPH_ENTITY_NOT_FOUND',
  GRAPH_CYCLE_DETECTED: 'GRAPH_CYCLE_DETECTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
